name: ci-package
on:
  push:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  windows:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Fetch Sources
      run: git fetch --no-tags --depth=1 origin master

    - uses: ssciwr/doxygen-install@v1

    - name: Download Packages
      shell: powershell
      run: |
        md c:\projects\install
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-win.zip", "c:\projects\install\ninja.zip")

    - name: Set Version
      id: version
      run: echo "version_number=2.6.20282" >> "$GITHUB_OUTPUT"

    - name: Build Package
      working-directory: ${{ github.workspace }}
      shell: cmd
      run: |
        echo ------ Setting up paths ------
        7z x c:\projects\install\ninja.zip -oc:\projects\install\ninja > nul
        set PATH=c:\projects\install\ninja;%PATH%
        dir "c:\Program Files (x86)\WiX Toolset"*
        set PATH=C:\Program Files (x86)\WiX Toolset v3.14\bin;%PATH%
        call "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Auxiliary/Build/vcvars32.bat"
        echo ------ Running suite ------
        echo PATH is "%PATH%"
        echo Running in directory "%CD%"
        perl tests/runsuite_wrapper.pl travis use_ninja
      env:
        CI_TARGET: package
        VERSION_NUMBER: ${{ steps.version.outputs.version_number }}

    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: windows-zip
        path: DrMemory-Windows-${{ steps.version.outputs.version_number }}.zip

    - name: Upload Msi
      uses: actions/upload-artifact@v4
      with:
        name: windows-msi
        path: DrMemory-Windows-${{ steps.version.outputs.version_number }}.msi

  create_release:
    needs: [windows]
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Set Version
      id: version
      run: |
        echo "version_number=2.6.20282" >> "$GITHUB_OUTPUT"
        echo "version_string=release_2.6.20282" >> "$GITHUB_OUTPUT"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.version_string }}
        release_name: ${{ steps.version.outputs.version_string }}
        body: |
          Auto-generated periodic build.
        draft: false
        prerelease: false

    - name: Download Zip
      uses: actions/download-artifact@v4
      with:
        name: windows-zip

    - name: Upload Zip
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: DrMemory-Windows-${{ steps.version.outputs.version_number }}.zip
        asset_name: DrMemory-Windows-${{ steps.version.outputs.version_number }}.zip
        asset_content_type: application/zip

    - name: Download Msi
      uses: actions/download-artifact@v4
      with:
        name: windows-msi

    - name: Upload Msi
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: DrMemory-Windows-${{ steps.version.outputs.version_number }}.msi
        asset_name: DrMemory-Windows-${{ steps.version.outputs.version_number }}.msi
        asset_content_type: application/octet-stream